name: Deploy to GitHub Pages
jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages/deploy # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
